# -*- coding: utf-8 -*-

"""
youtube

This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
"""


class TestEnum(object):

    """Implementation of the 'TestEnum' enum.

    This is the test description of enum00

    Attributes:
        FIRSTFILED: Test description of first filed
        SECONDFIELD: Test description of Second filed
        THIRD VALUE: TODO: type description here.

    """

    FIRSTFILED = 22

    SECONDFIELD = 23

    THIRD_VALUE = 66
