/*
 * YoutubeLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

package localhost5001.models;

import java.util.ArrayList;
import java.util.List;
import java.util.TreeMap;

/**
 * TestEnum to be used.
 */
public enum TestEnum {
    /**
     * Test description of first filed
     */
    FIRSTFILED,

    /**
     * Test description of Second filed
     */
    SECONDFIELD,

    THIRD_VALUE;


    private static TreeMap<Integer, TestEnum> valueMap = new TreeMap<>();
    private Integer value;

    static {
        FIRSTFILED.value = 22;
        SECONDFIELD.value = 23;
        THIRD_VALUE.value = 66;

        valueMap.put(22, FIRSTFILED);
        valueMap.put(23, SECONDFIELD);
        valueMap.put(66, THIRD_VALUE);
    }

    /**
     * Returns the enum member associated with the given integer value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given integer value.
     */
    @com.fasterxml.jackson.annotation.JsonCreator
    public static TestEnum fromInteger(Integer toConvert) {
        return valueMap.get(toConvert);
    }

    /**
     * Returns the integer value associated with the enum member.
     * @return The integer value against enum member.
     */
    @com.fasterxml.jackson.annotation.JsonValue
    public Integer value() {
        return value;
    }
        
    /**
     * Get string representation of this enum.
     */
    @Override
    public String toString() {
        return value.toString();
    }

    /**
     * Convert list of TestEnum values to list of integer values.
     * @param toConvert The list of TestEnum values to convert.
     * @return List of representative integer values.
     */
    public static List<Integer> toValue(List<TestEnum> toConvert) {
        if (toConvert == null) {
            return null;
        }
        List<Integer> convertedValues = new ArrayList<>();
        for (TestEnum enumValue : toConvert) {
            convertedValues.add(enumValue.value);
        }
        return convertedValues;
    }
} 