/*
 * YoutubeLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

package localhost5001.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for WeatherForcaseJsonImported type.
 */
public class WeatherForcaseJsonImported {
    private String date;
    private int temperatureC;
    private int temperatureF;
    private String summary;

    /**
     * Default constructor.
     */
    public WeatherForcaseJsonImported() {
    }

    /**
     * Initialization constructor.
     * @param  date  String value for date.
     * @param  temperatureC  int value for temperatureC.
     * @param  temperatureF  int value for temperatureF.
     * @param  summary  String value for summary.
     */
    public WeatherForcaseJsonImported(
            String date,
            int temperatureC,
            int temperatureF,
            String summary) {
        this.date = date;
        this.temperatureC = temperatureC;
        this.temperatureF = temperatureF;
        this.summary = summary;
    }

    /**
     * Getter for Date.
     * @return Returns the String
     */
    @JsonGetter("date")
    public String getDate() {
        return date;
    }

    /**
     * Setter for Date.
     * @param date Value for String
     */
    @JsonSetter("date")
    public void setDate(String date) {
        this.date = date;
    }

    /**
     * Getter for TemperatureC.
     * @return Returns the int
     */
    @JsonGetter("temperatureC")
    public int getTemperatureC() {
        return temperatureC;
    }

    /**
     * Setter for TemperatureC.
     * @param temperatureC Value for int
     */
    @JsonSetter("temperatureC")
    public void setTemperatureC(int temperatureC) {
        this.temperatureC = temperatureC;
    }

    /**
     * Getter for TemperatureF.
     * @return Returns the int
     */
    @JsonGetter("temperatureF")
    public int getTemperatureF() {
        return temperatureF;
    }

    /**
     * Setter for TemperatureF.
     * @param temperatureF Value for int
     */
    @JsonSetter("temperatureF")
    public void setTemperatureF(int temperatureF) {
        this.temperatureF = temperatureF;
    }

    /**
     * Getter for Summary.
     * @return Returns the String
     */
    @JsonGetter("summary")
    public String getSummary() {
        return summary;
    }

    /**
     * Setter for Summary.
     * @param summary Value for String
     */
    @JsonSetter("summary")
    public void setSummary(String summary) {
        this.summary = summary;
    }

    /**
     * Converts this WeatherForcaseJsonImported into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "WeatherForcaseJsonImported [" + "date=" + date + ", temperatureC=" + temperatureC
                + ", temperatureF=" + temperatureF + ", summary=" + summary + "]";
    }

    /**
     * Builds a new {@link WeatherForcaseJsonImported.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link WeatherForcaseJsonImported.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(date, temperatureC, temperatureF, summary);
        return builder;
    }

    /**
     * Class to build instances of {@link WeatherForcaseJsonImported}.
     */
    public static class Builder {
        private String date;
        private int temperatureC;
        private int temperatureF;
        private String summary;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  date  String value for date.
         * @param  temperatureC  int value for temperatureC.
         * @param  temperatureF  int value for temperatureF.
         * @param  summary  String value for summary.
         */
        public Builder(String date, int temperatureC, int temperatureF, String summary) {
            this.date = date;
            this.temperatureC = temperatureC;
            this.temperatureF = temperatureF;
            this.summary = summary;
        }

        /**
         * Setter for date.
         * @param  date  String value for date.
         * @return Builder
         */
        public Builder date(String date) {
            this.date = date;
            return this;
        }

        /**
         * Setter for temperatureC.
         * @param  temperatureC  int value for temperatureC.
         * @return Builder
         */
        public Builder temperatureC(int temperatureC) {
            this.temperatureC = temperatureC;
            return this;
        }

        /**
         * Setter for temperatureF.
         * @param  temperatureF  int value for temperatureF.
         * @return Builder
         */
        public Builder temperatureF(int temperatureF) {
            this.temperatureF = temperatureF;
            return this;
        }

        /**
         * Setter for summary.
         * @param  summary  String value for summary.
         * @return Builder
         */
        public Builder summary(String summary) {
            this.summary = summary;
            return this;
        }

        /**
         * Builds a new {@link WeatherForcaseJsonImported} object using the set fields.
         * @return {@link WeatherForcaseJsonImported}
         */
        public WeatherForcaseJsonImported build() {
            return new WeatherForcaseJsonImported(date, temperatureC, temperatureF, summary);
        }
    }
}
