/*
 * YoutubeLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

package localhost5001.exceptions;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import localhost5001.http.client.HttpContext;

/**
 * This is a model class for ProblemDetailsException type.
 */
public class ProblemDetailsException
        extends ApiException {
    private static final long serialVersionUID = 5821497372297366749L;
    private String type;
    private String title;
    private int status;
    private String traceId;

    /**
     * Initialization constructor.
     * @param   reason  The reason for throwing exception
     * @param   context The http context of the API exception
     */
    public ProblemDetailsException(String reason, HttpContext context) {
        super(reason, context);
    }


    /**
     * Getter for Type.
     * @return Returns the String
     */
    @JsonGetter("type")
    public String getType() {
        return this.type;
    }

    /**
     * Setter for Type.
     * @param type Value for String
     */
    @JsonSetter("type")
    private void setType(String type) {
        this.type = type;
    }

    /**
     * Getter for Title.
     * @return Returns the String
     */
    @JsonGetter("title")
    public String getTitle() {
        return this.title;
    }

    /**
     * Setter for Title.
     * @param title Value for String
     */
    @JsonSetter("title")
    private void setTitle(String title) {
        this.title = title;
    }

    /**
     * Getter for Status.
     * @return Returns the int
     */
    @JsonGetter("status")
    public int getStatus() {
        return this.status;
    }

    /**
     * Setter for Status.
     * @param status Value for int
     */
    @JsonSetter("status")
    private void setStatus(int status) {
        this.status = status;
    }

    /**
     * Getter for TraceId.
     * @return Returns the String
     */
    @JsonGetter("traceId")
    public String getTraceId() {
        return this.traceId;
    }

    /**
     * Setter for TraceId.
     * @param traceId Value for String
     */
    @JsonSetter("traceId")
    private void setTraceId(String traceId) {
        this.traceId = traceId;
    }
}
