# -*- coding: utf-8 -*-

"""
youtube

This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
"""

from youtube.api_helper import APIHelper
import youtube.exceptions.api_exception


class ProblemDetailsException(youtube.exceptions.api_exception.APIException):
    def __init__(self, reason, response):
        """Constructor for the ProblemDetailsException class

        Args:
            reason (string): The reason (or error message) for the Exception
                to be raised.
            response (HttpResponse): The HttpResponse of the API call.

        """
        super(ProblemDetailsException, self).__init__(reason, response)
        dictionary = APIHelper.json_deserialize(self.response.text)
        if isinstance(dictionary, dict):
            self.unbox(dictionary)

    def unbox(self, dictionary):
        """Populates the properties of this object by extracting them from a dictionary.

        Args:
            dictionary (dictionary): A dictionary representation of the object as
            obtained from the deserialization of the server's response. The keys
            MUST match property names in the API description.

        """
        self.mtype = dictionary.get('type')
        self.title = dictionary.get('title')
        self.status = dictionary.get('status')
        self.trace_id = dictionary.get('traceId')
